# Generated by Django 5.2 on 2025-04-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iTop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='kwh_historico_consumo',
            field=models.TextField(),
        ),
    ]
