# Generated by Django 5.2 on 2025-04-15 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iTop', '0002_alter_lead_kwh_historico_consumo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='lead',
            table='nz_lead_tmp',
        ),
    ]
