# Generated by Django 5.2 on 2025-04-15 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iTop', '0003_alter_lead_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={'managed': False},
        ),
    ]
