# Generated by Django 5.2 on 2025-04-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iTop', '0004_alter_lead_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_lead', models.CharField(max_length=100)),
                ('arquivo', models.FileField(upload_to='pdfs/')),
                ('texto_extraido', models.TextField()),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
