# Generated by Django 5.2 on 2025-04-15 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iTop', '0005_contapdf'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContaPDF',
        ),
    ]
